# Generated by Django 5.0.3 on 2024-03-08 09:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('CompanyID', models.AutoField(primary_key=True, serialize=False)),
                ('Email', models.EmailField(max_length=254)),
                ('Companyname', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployID', models.AutoField(primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=255, unique=True)),
                ('Firstname', models.CharField(max_length=255)),
                ('Lastname', models.CharField(max_length=255)),
                ('Password', models.CharField(max_length=255)),
                ('Role', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('CompanyID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VacayVue.companies')),
            ],
        ),
        migrations.CreateModel(
            name='Requests',
            fields=[
                ('RequestID', models.AutoField(primary_key=True, serialize=False)),
                ('StartDate', models.DateField()),
                ('EndDate', models.DateField()),
                ('Type', models.CharField(max_length=50)),
                ('Status', models.CharField(max_length=50)),
                ('Comments', models.TextField(blank=True)),
                ('EmployID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VacayVue.employees')),
            ],
        ),
    ]
