# Generated by Django 5.0.3 on 2024-03-19 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='CompanyID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='VacayVue.companies'),
        ),
        migrations.AlterField(
            model_name='requests',
            name='EmployID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='requests', to='VacayVue.employees'),
        ),
    ]
