# Generated by Django 5.0.3 on 2024-05-01 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='default_days',
            field=models.IntegerField(default=1),
        ),
    ]
