# Generated by Django 5.0.3 on 2024-03-22 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='companies',
            old_name='CompanyID',
            new_name='companyID',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='Companyname',
            new_name='companyname',
        ),
        migrations.RenameField(
            model_name='companies',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='CompanyID',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='employees',
            old_name='EmployID',
            new_name='employID',
        ),
    ]
