# Generated by Django 5.0.3 on 2024-05-17 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='leave_type',
            field=models.ForeignKey(default='Κανονική Άδεια', on_delete=django.db.models.deletion.CASCADE, to='VacayVue.leavetype'),
        ),
    ]
