# Generated by Django 5.0.3 on 2024-03-21 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0002_alter_employees_companyid_alter_requests_employid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='Firstname',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='Lastname',
        ),
        migrations.AddField(
            model_name='employees',
            name='join_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='EndDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='requests',
            name='StartDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
