# Generated by Django 5.0.3 on 2024-03-28 11:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0002_alter_employees_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VacayVue.companies'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='VacayVue.companies'),
        ),
    ]
