# Generated by Django 5.0.3 on 2024-03-22 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0002_rename_companyid_companies_companyid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='hrname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
