# Generated by Django 5.0.3 on 2024-05-17 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0003_alter_balance_leave_type_alter_request_leave_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavetype',
            name='balance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='VacayVue.balance'),
        ),
        migrations.AlterField(
            model_name='balance',
            name='leave_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances', to='VacayVue.leavetype'),
        ),
    ]
