# Generated by Django 5.0.3 on 2024-03-22 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0003_companies_hrname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='companyname',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
