# Generated by Django 5.0.3 on 2024-05-02 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0003_alter_leavetype_default_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='name',
            field=models.CharField(choices=[('Κανονική Άδεια', 'Κανονική Άδεια'), ('Αδεια Εξετάσεων Εργαζόμενων Σπουδαστών', 'Αδεια Εξετάσεων Εργαζόμενων Σπουδαστών'), ('Αδεια Εξετάσεων Μεταπτυχιακών Φοιτητών', 'Αδεια Εξετάσεων Μεταπτυχιακών Φοιτητών'), ('Αιμοδοτική Άδεια', 'Αιμοδοτική Άδεια'), ('Άδεια Άνευ Αποδοχών', 'Άδεια Άνευ Αποδοχών'), ('Άδεια Μητρότητας', 'Άδεια Μητρότητας'), ('Άδεια Πατρότητας', 'Άδεια Πατρότητας')], default='Κανονική Άδεια', max_length=100),
        ),
    ]
