# Generated by Django 5.0.3 on 2024-03-29 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0004_remove_employees_company_remove_employees_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='join_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
