# Generated by Django 5.0.3 on 2024-05-17 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0004_leavetype_balance_alter_balance_leave_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leavetype',
            name='balance',
        ),
    ]
