# Generated by Django 5.0.3 on 2024-05-08 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0004_alter_leavetype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leavetype',
            name='reset_month',
            field=models.IntegerField(choices=[(1, 'Ιανουάριος'), (2, 'Φεβρουάριος'), (3, 'Μάρτιος'), (4, 'Απρίλιος'), (5, 'Μάιος'), (6, 'Ιούνιος'), (7, 'Ιούλιος'), (8, 'Αύγουστος'), (9, 'Σεπτέμβριος'), (10, 'Οκτώβριος'), (11, 'Νοέμβριος'), (12, 'Δεκέμβριος')], default=1),
        ),
        migrations.DeleteModel(
            name='LeaveBalance',
        ),
    ]
