# Generated by Django 5.0.3 on 2024-03-22 11:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0004_alter_companies_companyname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='users',
        ),
        migrations.RemoveField(
            model_name='employees',
            name='user_type',
        ),
        migrations.AddField(
            model_name='companies',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='employees',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee', to=settings.AUTH_USER_MODEL),
        ),
    ]
