# Generated by Django 5.0.3 on 2024-03-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0005_remove_companies_users_remove_employees_user_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='username',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
