# Generated by Django 5.0.3 on 2024-05-20 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0005_remove_leavetype_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='document',
            field=models.FileField(blank=True, null=True, upload_to='documents/'),
        ),
    ]
