# Generated by Django 5.0.3 on 2024-03-21 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0005_remove_employees_join_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='companies',
            name='Email',
            field=models.EmailField(default='admin@test.gr', max_length=254, unique=True),
        ),
    ]
