# Generated by Django 5.0.3 on 2024-03-12 07:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0005_remove_requests_employid_employees_requestid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='RequestID',
        ),
        migrations.AddField(
            model_name='requests',
            name='EmployID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VacayVue.employees'),
        ),
    ]
