# Generated by Django 5.0.3 on 2024-03-22 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0006_companies_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companies',
            name='username',
        ),
    ]
