# Generated by Django 5.0.3 on 2024-03-21 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0006_companies_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companies',
            name='Email',
            field=models.EmailField(max_length=254, unique=True),
        ),
    ]
