# Generated by Django 5.0.3 on 2024-05-08 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0006_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='balance',
            name='remaining_days',
            field=models.IntegerField(default=0),
        ),
    ]
