# Generated by Django 5.0.3 on 2024-05-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0007_alter_customuser_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('υπάλληλο', 'Υπάλληλο'), ('εταιρία', 'Εταιρία'), ('διαχειριστής', 'Διαχειριστής')], max_length=20),
        ),
    ]
