# Generated by Django 5.0.3 on 2024-03-22 13:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0007_remove_companies_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='employID',
            new_name='employeeID',
        ),
        migrations.RemoveField(
            model_name='companies',
            name='user',
        ),
        migrations.AddField(
            model_name='customuser',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='VacayVue.companies'),
        ),
        migrations.AlterField(
            model_name='companies',
            name='companyname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='companies',
            name='hrname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='employees',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profiles', to='VacayVue.companies'),
        ),
        migrations.AlterField(
            model_name='employees',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='employee_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
