# Generated by Django 5.0.3 on 2024-03-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0007_alter_companies_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='employees',
            name='join_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='employees',
            name='username',
            field=models.CharField(max_length=225, null=True),
        ),
    ]
