# Generated by Django 5.0.3 on 2024-03-12 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0007_events'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
