# Generated by Django 5.0.3 on 2024-05-23 12:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0009_customholidays'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customholidays',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_set_holiday', to=settings.AUTH_USER_MODEL),
        ),
    ]
