# Generated by Django 5.0.3 on 2024-03-13 11:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0010_events_delete_calendar'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AddField(
            model_name='events',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
