# Generated by Django 5.0.3 on 2024-03-13 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0011_events_created_at_events_updated_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={'verbose_name': 'Calendar Event', 'verbose_name_plural': 'Calendar Events'},
        ),
    ]
