# Generated by Django 5.0.3 on 2024-03-13 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0012_alter_events_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='events',
            options={},
        ),
        migrations.RemoveField(
            model_name='events',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='events',
            name='description',
        ),
        migrations.RemoveField(
            model_name='events',
            name='updated_at',
        ),
        migrations.AlterModelTable(
            name='events',
            table='tblevents',
        ),
    ]
