# Generated by Django 5.0.3 on 2024-03-13 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0013_alter_events_options_remove_events_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requests',
            name='Status',
            field=models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('pending', 'Pending')], default='pending', max_length=50),
        ),
    ]
