# Generated by Django 5.0.3 on 2024-03-15 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('VacayVue', '0015_rename_event_id_events_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requests',
            old_name='RequestID',
            new_name='request_id',
        ),
    ]
